рк3
java-park-mail-ru/scissors-02-2017 pull request #5
Opened 2017-05-07 09:52 UTC by imabu

2017-05-11 10:31 UTC, KSolovyev requested changes

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/config/WebSocketConfig.java
> +                .setAllowedOrigins("*");
с таким Origin, клиент может не послать куку. Нужен конкретный домен

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/mechanic/GameMechanic.java
> +        final Deathmatch setting = resourseFactory.get("game/deathmatch.json", Deathmatch.class);
typo `settings`

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/mechanic/GameMechanic.java
> +    private  int NUMBER_PLAYERS;
сделайте в классе реформат, пожалуйста

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/transport/websocket/GameSocketHandler.java
> +    /*protected void handleTextMessage(WebSocketSession session, TextMessage message) throws AuthenticationException {
не работает, видимо, из-за неправильного origin

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/services/GameService.java
> +                        final Bullet bullet = resourseFactory.get(descriptor, Bullet.class);
вот здесь вы в тике механики обращаетесь к диску. Так делать нельзя, нужно загрузить все ресурсы в память при старте и положить их в карту

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/services/GameService.java
> +                    player.setDesirablePosition(new Coords(snap.getX(), snap.getY()));
перемещения должны быть реализованы на сервере. Клиент должен выступать, в данном случае, терминалом. Нельзя передавать в снимке координаты перемещения.

2017-05-11 10:31 UTC, KSolovyev commented on src/main/java/game/services/GameService.java
> +                            bullet.setDesirablePosition(snapBullet.getPresentPosition());
а пули уж точно должны жить только на сервере

2017-05-11 10:35 UTC, imabu commented on src/main/java/game/mechanic/GameMechanic.java
> +    private  int NUMBER_PLAYERS;
а что это значит?

2017-05-11 10:54 UTC, KSolovyev commented on src/main/java/game/mechanic/GameMechanic.java
> +    private  int NUMBER_PLAYERS;
Code -> reformat code

2017-05-24 08:38 UTC, KSolovyev commented
Отпишитесь, пожалуйста, как поправите

2017-06-01 21:06 UTC, KSolovyev commented
работает ли игра? Можно ссылку?

2017-06-02 15:51 UTC, imabu commented
На фронте нет реализации мультиплеера

2017-06-02 16:38 UTC, KSolovyev commented
жаль

2017-09-18 10:19 UTC, merged